# Generated by Django 4.2.4 on 2023-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_confirm_key_user_email_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirm_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
