# Generated by Django 4.2.4 on 2023-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
