# Generated by Django 4.2.4 on 2023-08-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_publication_sign_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
