# Generated by Django 4.2.4 on 2023-08-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_active',
            new_name='is_current',
        ),
    ]
