# Generated by Django 4.2.4 on 2023-08-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_user_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_owned',
            new_name='lashed',
        ),
    ]
