# Generated by Django 4.2.4 on 2023-08-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_is_current'),
        ('catalog', '0012_rename_user_owned_product_lashed'),
    ]

    operations = [
    ]
