# Generated by Django 4.2.4 on 2023-08-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_user_owned_product_lashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_published_status', 'Can publish post')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
