# Generated by Django 4.2.4 on 2023-08-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_is_current'),
        ('catalog', '0016_alter_product_is_active'),
    ]

    operations = [
    ]
